### ISSUE TITLE
There is no method available in the module

### ISSUE THREAD

**Issue by EwainCai** [conda-forge/clickhouse-cityhash-feedstock#12]
```
>>> import clickhouse_cityhash
>>> print(dir(clickhouse_cityhash))
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```
How to use this module

**Comment by xzkostyan** [comment]
This module is not intended for direct usage. But you can list all functions:

```python
In [3]: from clickhouse_cityhash import cityhash                                                                                                                                

In [4]: dir(cityhash)                                                                                                                                                           
Out[4]: 
['CityHash128',
 'CityHash128WithSeed',
 'CityHash64',
 'CityHash64WithSeed',
 'CityHash64WithSeeds',
 '__all__',
 '__author__',
 '__builtins__',
 '__doc__',
 '__email__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__test__',
 '__version__']
```

**Comment by EwainCai** [comment]
```
>>> from clickhouse_cityhash import cityhash
>>> print(CityHash64('index'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'CityHash64' is not defined
```
How should I use this method: CityHash64

**Comment by xzkostyan** [comment]
```python
In [1]: from clickhouse_cityhash import cityhash                                                                                                                                

In [2]: cityhash.CityHash64('test')                                                                                                                                             
Out[2]: 17703940110308125106
```

**Comment by EwainCai** [comment]
> ```python
> In [1]: from clickhouse_cityhash import cityhash                                                                                                                                
> 
> In [2]: cityhash.CityHash64('test')                                                                                                                                             
> Out[2]: 17703940110308125106
> ```

ok,thank you!

**Comment by EwainCai** [comment]
> > ```python
> > In [1]: from clickhouse_cityhash import cityhash                                                                                                                                
> > 
> > In [2]: cityhash.CityHash64('test')                                                                                                                                             
> > Out[2]: 17703940110308125106
> > ```
> 
> ok,thank you!
My personal project is built using java, how can I use java to call clickhouse-cityhash

**Comment by EwainCai** [comment]
I already know how to call, thanks
